language: c

arch:
  - arm64
  - ppc64le
  - s390x
os: linux
compiler:
  - gcc
  - clang

install: skip

stages:
  - Test
  - Arch-Release

jobs:
  include:
    - stage: Test
      script:
        - echo Stage 1
    - stage: Arch-Release
      script:
        - echo Stage 2

